INSERT INTO compartment_templates (apparatus_type, name, compartment_type, sort_order) VALUES
('Engine','Cab','Cab',1),('Engine','EMS Cabinet','EMS Cabinet',2),('Engine','Driver Side 1','Driver Side',3),('Engine','Officer Side 1','Officer Side',4),('Engine','Driver Side Wheel Well 1','Driver Side Wheel Well',5),('Engine','Officer Side Wheel Well 1','Officer Side Wheel Well',6),('Engine','Rear Driver Side','Rear Driver Side',7),('Engine','Rear Center','Rear Center',8),('Engine','Rear Officer Side','Rear Officer Side',9),
('Engine With Walkway','Cab','Cab',1),('Engine With Walkway','EMS Cabinet','EMS Cabinet',2),('Engine With Walkway','Driver Side 1','Driver Side',3),('Engine With Walkway','Officer Side 1','Officer Side',4),('Engine With Walkway','Driver Side Wheel Well 1','Driver Side Wheel Well',5),('Engine With Walkway','Officer Side Wheel Well 1','Officer Side Wheel Well',6),('Engine With Walkway','Driver Side Walkway','Driver Side Walkway',7),('Engine With Walkway','Officer Side Walkway','Officer Side Walkway',8),('Engine With Walkway','Rear Driver Side','Rear Driver Side',9),('Engine With Walkway','Rear Center','Rear Center',10),('Engine With Walkway','Rear Officer Side','Rear Officer Side',11),
('Truck','Cab','Cab',1),('Truck','EMS Cabinet','EMS Cabinet',2),('Truck','Driver Side 1','Driver Side',3),('Truck','Officer Side 1','Officer Side',4),('Truck','Driver Side Wheel Well 1','Driver Side Wheel Well',5),('Truck','Officer Side Wheel Well 1','Officer Side Wheel Well',6),('Truck','Rear Driver Side','Rear Driver Side',7),('Truck','Rear Center','Rear Center',8),('Truck','Rear Officer Side','Rear Officer Side',9),('Truck','Ladder','Ladder',10),
('Truck 1','Cab','Cab',1),('Truck 1','EMS Cabinet','EMS Cabinet',2),('Truck 1','Driver Side 1','Driver Side',3),('Truck 1','Officer Side 1','Officer Side',4),('Truck 1','Driver Side Wheel Well 1','Driver Side Wheel Well',5),('Truck 1','Officer Side Wheel Well 1','Officer Side Wheel Well',6),('Truck 1','Rear Driver Side','Rear Driver Side',7),('Truck 1','Rear Center','Rear Center',8),('Truck 1','Rear Officer Side','Rear Officer Side',9),('Truck 1','Ladder','Ladder',10),('Truck 1','Driver Side Bucket Box','Bucket Box',11),('Truck 1','Officer Side Bucket Box','Bucket Box',12),('Truck 1','Bucket','Bucket',13);
INSERT INTO apparatus (name,type,station_number,is_reserve,status) VALUES
('Engine 1','Engine','1',0,'Active'),('Truck 1','Truck 1','1',0,'Active'),('Truck 3','Truck','1',0,'Active'),('Rescue 1','Rescue','1',0,'Active'),('Battalion 1','Command','1',0,'Active'),('Truck 2','Truck','2',0,'Active'),('Engine 10','Engine','2',0,'Active'),('Engine 3','Engine','3',0,'Active'),('Engine 4','Engine','4',0,'Active'),('Engine 5','Engine','5',0,'Active'),('Engine 6','Engine','6',0,'Active'),('Engine 7','Engine','7',0,'Active'),('Engine 9','Reserve Engine','1',1,'Active');
INSERT INTO compartments (apparatus_id,name,compartment_type,sort_order)
SELECT a.id,t.name,t.compartment_type,t.sort_order FROM apparatus a JOIN compartment_templates t ON t.apparatus_type = CASE WHEN a.type='Reserve Engine' THEN 'Engine' ELSE a.type END WHERE t.apparatus_type IN ('Engine','Truck','Truck 1');
