export interface Env { DB: D1Database }
const ok=(data:unknown,status=200)=>new Response(data===undefined?null:JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'}});
const body=(r:Request)=>r.json() as Promise<Record<string,unknown>>;
const apparatusSelect=`SELECT a.*, COUNT(DISTINCT c.id) compartment_count, COUNT(DISTINCT i.id) item_count FROM apparatus a LEFT JOIN compartments c ON c.apparatus_id=a.id LEFT JOIN inventory_items i ON i.apparatus_id=a.id`;
async function createTemplateCompartments(db:D1Database, apparatusId:number, template:string){ if(template==='Blank/custom') return; await db.prepare(`INSERT INTO compartments (apparatus_id,name,compartment_type,sort_order) SELECT ?,name,compartment_type,sort_order FROM compartment_templates WHERE apparatus_type=? ORDER BY sort_order`).bind(apparatusId,template).run(); }
export default { async fetch(request:Request, env:Env){
 if(request.method==='OPTIONS') return ok(undefined,204); const url=new URL(request.url); const p=url.pathname.split('/').filter(Boolean);
 try{
  if(p[0]!=='api') return new Response('Not found',{status:404});
  if(p[1]==='apparatus' && p.length===2 && request.method==='GET') return ok((await env.DB.prepare(`${apparatusSelect} GROUP BY a.id ORDER BY a.station_number,a.name`).all()).results);
  if(p[1]==='apparatus' && p.length===2 && request.method==='POST'){ const b=await body(request); const res=await env.DB.prepare(`INSERT INTO apparatus (name,type,station_number,is_reserve,status,notes) VALUES (?,?,?,?,?,?)`).bind(b.name,b.type,b.station_number,b.is_reserve?1:0,b.status||'Active',b.notes||null).run(); await createTemplateCompartments(env.DB, Number(res.meta.last_row_id), String(b.template||b.type)); return ok((await env.DB.prepare(`${apparatusSelect} WHERE a.id=? GROUP BY a.id`).bind(res.meta.last_row_id).first()),201); }
  if(p[1]==='apparatus' && p.length===3 && request.method==='GET') return ok(await env.DB.prepare(`${apparatusSelect} WHERE a.id=? GROUP BY a.id`).bind(p[2]).first());
  if(p[1]==='apparatus' && p.length===3 && request.method==='PUT'){ const b=await body(request); await env.DB.prepare(`UPDATE apparatus SET name=?,type=?,station_number=?,is_reserve=?,status=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.name,b.type,b.station_number,b.is_reserve?1:0,b.status,b.notes,p[2]).run(); return ok(await env.DB.prepare(`${apparatusSelect} WHERE a.id=? GROUP BY a.id`).bind(p[2]).first()); }
  if(p[1]==='apparatus' && p.length===3 && request.method==='DELETE'){ await env.DB.prepare(`DELETE FROM apparatus WHERE id=?`).bind(p[2]).run(); return ok(undefined,204); }
  if(p[1]==='apparatus' && p[3]==='compartments' && request.method==='GET') return ok((await env.DB.prepare(`SELECT * FROM compartments WHERE apparatus_id=? ORDER BY sort_order,name`).bind(p[2]).all()).results);
  if(p[1]==='apparatus' && p[3]==='compartments' && request.method==='POST'){ const b=await body(request); const r=await env.DB.prepare(`INSERT INTO compartments (apparatus_id,name,compartment_type,sort_order,notes) VALUES (?,?,?,?,?)`).bind(p[2],b.name,b.compartment_type,b.sort_order||0,b.notes||null).run(); return ok(await env.DB.prepare(`SELECT * FROM compartments WHERE id=?`).bind(r.meta.last_row_id).first(),201); }
  if(p[1]==='compartments' && request.method==='PUT'){ const b=await body(request); await env.DB.prepare(`UPDATE compartments SET name=?,compartment_type=?,sort_order=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.name,b.compartment_type,b.sort_order||0,b.notes||null,p[2]).run(); return ok(await env.DB.prepare(`SELECT * FROM compartments WHERE id=?`).bind(p[2]).first()); }
  if(p[1]==='compartments' && request.method==='DELETE'){ await env.DB.prepare(`DELETE FROM compartments WHERE id=?`).bind(p[2]).run(); return ok(undefined,204); }
  if(p[1]==='apparatus' && p[3]==='items' && request.method==='GET') return ok((await env.DB.prepare(`SELECT * FROM inventory_items WHERE apparatus_id=? ORDER BY name`).bind(p[2]).all()).results);
  if(p[1]==='items' && request.method==='POST'){ const b=await body(request); const r=await env.DB.prepare(`INSERT INTO inventory_items (apparatus_id,compartment_id,name,equipment_type,equipment_id,serial_number,quantity,make,model,description,notes,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(b.apparatus_id,b.compartment_id,b.name,b.equipment_type,String(b.equipment_id||''),String(b.serial_number||''),b.quantity||1,b.make||null,b.model||null,b.description||null,b.notes||null,b.status||'In Service').run(); return ok(await env.DB.prepare(`SELECT * FROM inventory_items WHERE id=?`).bind(r.meta.last_row_id).first(),201); }
  if(p[1]==='items' && p[3]==='move' && request.method==='POST'){ const b=await body(request); await env.DB.prepare(`UPDATE inventory_items SET apparatus_id=?,compartment_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.apparatus_id,b.compartment_id,p[2]).run(); return ok(await env.DB.prepare(`SELECT * FROM inventory_items WHERE id=?`).bind(p[2]).first()); }
  if(p[1]==='items' && request.method==='PUT'){ const b=await body(request); await env.DB.prepare(`UPDATE inventory_items SET apparatus_id=?,compartment_id=?,name=?,equipment_type=?,equipment_id=?,serial_number=?,quantity=?,make=?,model=?,description=?,notes=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.apparatus_id,b.compartment_id,b.name,b.equipment_type,String(b.equipment_id||''),String(b.serial_number||''),b.quantity||1,b.make||null,b.model||null,b.description||null,b.notes||null,b.status||'In Service',p[2]).run(); return ok(await env.DB.prepare(`SELECT * FROM inventory_items WHERE id=?`).bind(p[2]).first()); }
  if(p[1]==='items' && request.method==='DELETE'){ await env.DB.prepare(`DELETE FROM inventory_items WHERE id=?`).bind(p[2]).run(); return ok(undefined,204); }
 }catch(e){ return ok({error:e instanceof Error?e.message:String(e)},500); }
 return new Response('Not found',{status:404});
}};
