import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Plus, Search, Truck, LayoutDashboard, List } from 'lucide-react';
import { api } from './api';
import { APPARATUS_TEMPLATES, COMPARTMENT_TYPES, EQUIPMENT_TYPES, STATUSES, type Apparatus, type Compartment, type Item } from './types';
import './style.css';

function Shell(){return <BrowserRouter><div className="min-h-screen bg-slate-100 md:flex"><aside className="bg-navy text-white md:w-72 p-5"><h1 className="text-2xl font-bold">DFD Inventory</h1><p className="text-slate-300 mb-6">Apparatus by compartment</p><nav className="space-y-2"><NavLink className="nav" to="/"><LayoutDashboard/>Dashboard</NavLink><NavLink className="nav" to="/apparatus"><List/>Apparatus List</NavLink><NavLink className="nav" to="/apparatus/new"><Plus/>Add Apparatus</NavLink></nav></aside><main className="flex-1 p-4 md:p-8"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/apparatus" element={<ApparatusList/>}/><Route path="/apparatus/new" element={<AddApparatus/>}/><Route path="/apparatus/:id" element={<Detail/>}/></Routes></main></div></BrowserRouter>}
function Filters({q,setQ,type,setType,station,setStation,equip,setEquip}:{q:string;setQ:(v:string)=>void;type:string;setType:(v:string)=>void;station:string;setStation:(v:string)=>void;equip?:string;setEquip?:(v:string)=>void}){return <div className="card grid gap-3 md:grid-cols-4"><label className="field md:col-span-1"><span><Search size={16}/> Search</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search apparatus"/></label><label className="field"><span>Station</span><input value={station} onChange={e=>setStation(e.target.value)} placeholder="All stations"/></label><label className="field"><span>Apparatus type</span><input value={type} onChange={e=>setType(e.target.value)} placeholder="All types"/></label>{setEquip&&<label className="field"><span>Equipment type</span><select value={equip} onChange={e=>setEquip(e.target.value)}><option value="">All equipment</option>{EQUIPMENT_TYPES.map(x=><option key={x}>{x}</option>)}</select></label>}</div>}
function useApparatus(){const [rows,setRows]=useState<Apparatus[]>([]);useEffect(()=>{api.apparatus().then(setRows)},[]);return rows}
function filtered(rows:Apparatus[], q:string, type:string, station:string){return rows.filter(a=>(!q||a.name.toLowerCase().includes(q.toLowerCase()))&&(!type||a.type.toLowerCase().includes(type.toLowerCase()))&&(!station||a.station_number===station))}
function Dashboard(){const rows=useApparatus();const [q,setQ]=useState(''),[type,setType]=useState(''),[station,setStation]=useState('');const data=filtered(rows,q,type,station);return <><Header title="Dashboard"/><Filters q={q} setQ={setQ} type={type} setType={setType} station={station} setStation={setStation}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3 mt-5">{data.map(a=><div className="card" key={a.id}><Truck className="text-fire"/><h2 className="text-xl font-bold">{a.name}</h2><p>{a.type} • Station {a.station_number}</p><p className="mt-3 text-sm text-slate-600">{a.compartment_count} compartments • {a.item_count} items</p><Link className="btn mt-4" to={`/apparatus/${a.id}`}>Open apparatus</Link></div>)}</div></>}
function ApparatusList(){const rows=useApparatus();return <><Header title="Apparatus List"/><div className="card overflow-x-auto"><table><thead><tr>{['Apparatus Name','Type','Station','Status','Number of Compartments','Number of Items','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.type}</td><td>{a.station_number}</td><td>{a.status}</td><td>{a.compartment_count}</td><td>{a.item_count}</td><td><Link className="btn secondary" to={`/apparatus/${a.id}`}>Open/Edit</Link></td></tr>)}</tbody></table></div></>}
function Header({title}:{title:string}){return <div className="mb-5 flex items-center justify-between"><h1 className="text-3xl font-bold text-slate-900">{title}</h1><Link className="btn" to="/apparatus/new"><Plus/>Add Apparatus</Link></div>}
function AddApparatus(){const nav=useNavigate();const [form,set]=useState({name:'',type:'Engine',station_number:'1',is_reserve:false,template:'Engine'});async function submit(e:React.FormEvent){e.preventDefault();const a=await api.createApparatus(form);nav(`/apparatus/${a.id}`)}return <><Header title="Add Apparatus"/><form onSubmit={submit} className="card grid gap-4 md:grid-cols-2"><Input label="Apparatus name" value={form.name} onChange={v=>set({...form,name:v})}/><Input label="Apparatus type" value={form.type} onChange={v=>set({...form,type:v})}/><Input label="Station number" value={form.station_number} onChange={v=>set({...form,station_number:v})}/><label className="field"><span>Template selection</span><select value={form.template} onChange={e=>set({...form,template:e.target.value})}>{APPARATUS_TEMPLATES.map(t=><option key={t}>{t}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={form.is_reserve} onChange={e=>set({...form,is_reserve:e.target.checked})}/> Is reserve</label><button className="btn md:col-span-2">Create with template compartments</button></form></>}
function Detail(){const {id=''}=useParams();const [a,setA]=useState<Apparatus>();const [comps,setComps]=useState<Compartment[]>([]);const [items,setItems]=useState<Item[]>([]);const load=()=>{api.apparatusOne(id).then(setA);api.compartments(id).then(setComps);api.items(id).then(setItems)};useEffect(load,[id]);const grouped=useMemo(()=>comps.map(c=>({...c,items:items.filter(i=>i.compartment_id===c.id)})),[comps,items]);if(!a)return null;return <><Header title={a.name}/><div className="card mb-5"><h2 className="text-xl font-bold">{a.name}</h2><p>{a.type} • Station {a.station_number} • {a.status}</p></div><button className="btn mb-4" onClick={()=>editComp(Number(id),undefined,load)}>Add compartment</button><div className="grid gap-4">{grouped.map(c=><section className="card" key={c.id}><div className="flex flex-wrap justify-between gap-2"><div><h3 className="text-xl font-bold">{c.name}</h3><p className="text-sm text-slate-600">{c.compartment_type} • Sort {c.sort_order} • {c.notes}</p></div><div className="flex gap-2"><button className="btn" onClick={()=>editItem(a.id,c.id,undefined,comps,load)}>Add item</button><button className="btn secondary" onClick={()=>editComp(a.id,c,load)}>Edit compartment</button><button className="btn danger" onClick={async()=>confirm('Delete this compartment?')&&(await api.deleteCompartment(c.id),load())}>Delete</button></div></div><div className="mt-4 grid gap-2">{c.items.map(i=><div className="rounded border p-3 bg-slate-50" key={i.id}><b>{i.name}</b> <span className="text-sm">{i.equipment_type} • ID {i.equipment_id} • Serial {i.serial_number} • Qty {i.quantity} • {i.status}</span><p>{i.notes}</p><div className="mt-2 flex gap-2"><button className="btn secondary" onClick={()=>editItem(a.id,c.id,i,comps,load)}>Edit</button><button className="btn secondary" onClick={()=>moveItem(i,comps,load)}>Move</button><button className="btn danger" onClick={async()=>confirm('Delete this item?')&&(await api.deleteItem(i.id),load())}>Delete</button></div></div>)}</div></section>)}</div></>}
function Input({label,value,onChange}:{label:string;value:string|number;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
async function editComp(apparatus_id:number,c:Compartment|undefined,load:()=>void){const name=prompt('Compartment name',c?.name||''); if(!name)return; const compartment_type=prompt('Compartment type',c?.compartment_type||'Other')||'Other'; const sort_order=Number(prompt('Sort order',String(c?.sort_order||0))||0); const notes=prompt('Notes',c?.notes||'')||''; c?await api.updateCompartment(c.id,{name,compartment_type,sort_order,notes}):await api.createCompartment(apparatus_id,{name,compartment_type,sort_order,notes}); load()}
async function editItem(apparatus_id:number,compartment_id:number,i:Item|undefined,comps:Compartment[],load:()=>void){const name=prompt('Item name',i?.name||''); if(!name)return; const equipment_type=prompt('Equipment type',i?.equipment_type||EQUIPMENT_TYPES[0]); const equipment_id=prompt('Equipment ID (text; leading zeroes preserved)',i?.equipment_id||''); const serial_number=prompt('Serial number (text; leading zeroes preserved)',i?.serial_number||''); const quantity=Number(prompt('Quantity',String(i?.quantity||1))||1); const status=prompt('Status',i?.status||STATUSES[0])||STATUSES[0]; const notes=prompt('Notes',i?.notes||'')||''; const body={apparatus_id,compartment_id,name,equipment_type,equipment_id:String(equipment_id||''),serial_number:String(serial_number||''),quantity,status,notes}; i?await api.updateItem(i.id,body):await api.createItem(body); load()}
async function moveItem(i:Item, comps:Compartment[], load:()=>void){const choice=prompt('Move to compartment id:\n'+comps.map(c=>`${c.id}: ${c.name}`).join('\n'),String(i.compartment_id)); if(choice) {await api.moveItem(i.id,{compartment_id:Number(choice),apparatus_id:i.apparatus_id}); load()}}
createRoot(document.getElementById('root')!).render(<Shell/>);
